#!/usr/bin/env python3
"""
OpenFace 2.2 HOG Binary File Parser

Parses .hog files generated by OpenFace 2.2's FeatureExtraction tool.

Binary format (per frame):
- num_cols (int32)
- num_rows (int32)
- num_chan (int32) - typically 31 for FHOG
- frame_index (float32) - 1 value
- hog_features (float32 array) - num_rows * num_cols * num_chan values

Reference: OpenFace/matlab_runners/Demos/Read_HOG_file.m
"""

import numpy as np
import struct
from pathlib import Path
from typing import Tuple, Dict


class OF22HOGParser:
    """Parser for OpenFace 2.2 HOG binary files"""

    def __init__(self, hog_file_path: str):
        """
        Initialize parser

        Args:
            hog_file_path: Path to .hog file
        """
        self.hog_file_path = Path(hog_file_path)
        if not self.hog_file_path.exists():
            raise FileNotFoundError(f"HOG file not found: {hog_file_path}")

    def parse(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Parse HOG file and extract all frames

        Returns:
            Tuple of:
            - frame_indices: (n_frames,) array of frame numbers
            - hog_features: (n_frames, n_features) array of HOG descriptors
        """
        frame_indices = []
        hog_features = []

        with open(self.hog_file_path, 'rb') as f:
            while True:
                # Read header (num_cols, num_rows, num_chan)
                header_bytes = f.read(12)  # 3 * int32
                if len(header_bytes) < 12:
                    break  # End of file

                num_cols, num_rows, num_chan = struct.unpack('<iii', header_bytes)

                # Calculate feature vector size
                n_features = num_rows * num_cols * num_chan

                # Read frame index + HOG features
                n_values = 1 + n_features  # frame_index + features
                data_bytes = f.read(n_values * 4)  # float32 = 4 bytes each

                if len(data_bytes) < n_values * 4:
                    break  # Incomplete frame

                # Parse as float32 array
                frame_data = np.frombuffer(data_bytes, dtype=np.float32)

                frame_idx = frame_data[0]
                hog_feat = frame_data[1:]

                frame_indices.append(frame_idx)
                hog_features.append(hog_feat)

        if not frame_indices:
            raise ValueError(f"No valid frames found in {self.hog_file_path}")

        return np.array(frame_indices), np.array(hog_features)

    def get_frame(self, frame_number: int) -> Tuple[int, np.ndarray]:
        """
        Extract HOG features for a specific frame

        Args:
            frame_number: Frame index to extract (0-based)

        Returns:
            Tuple of (frame_index, hog_features)
        """
        frame_indices, hog_features = self.parse()

        if frame_number >= len(frame_indices):
            raise ValueError(
                f"Frame {frame_number} not found. "
                f"File contains {len(frame_indices)} frames (0-{len(frame_indices)-1})"
            )

        return int(frame_indices[frame_number]), hog_features[frame_number]


def main():
    """Test the HOG parser"""
    import pandas as pd

    hog_file = "/Users/johnwilsoniv/Documents/SplitFace Open3/S1 Face Mirror/of22_validation/IMG_0942_left_mirrored.hog"
    csv_file = "/Users/johnwilsoniv/Documents/SplitFace Open3/S1 Face Mirror/of22_validation/IMG_0942_left_mirrored.csv"

    print("=" * 80)
    print("OpenFace 2.2 HOG File Parser - Test")
    print("=" * 80)
    print(f"\nHOG file: {hog_file}")
    print(f"CSV file: {csv_file}\n")

    # Parse HOG file
    print("Parsing HOG file...")
    parser = OF22HOGParser(hog_file)
    frame_indices, hog_features = parser.parse()

    print(f"\n✓ Parsed {len(frame_indices)} frames")
    print(f"  Frame indices: {frame_indices[0]:.0f} to {frame_indices[-1]:.0f}")
    print(f"  HOG feature shape: {hog_features.shape}")
    print(f"  Features per frame: {hog_features.shape[1]}")

    # Load CSV file to compare
    print(f"\nLoading CSV file...")
    df = pd.read_csv(csv_file)
    print(f"✓ CSV contains {len(df)} rows")
    print(f"  Frame range: {df['frame'].min()} to {df['frame'].max()}")

    # Check alignment
    if len(frame_indices) == len(df):
        print(f"\n✓ HOG frames match CSV rows!")
    else:
        print(f"\n⚠️  Warning: HOG has {len(frame_indices)} frames, CSV has {len(df)} rows")

    # Show first few HOG features
    print(f"\nFirst frame HOG features (first 10 values):")
    print(f"  {hog_features[0, :10]}")

    # Statistics
    print(f"\nHOG feature statistics:")
    print(f"  Mean: {hog_features.mean():.6f}")
    print(f"  Std:  {hog_features.std():.6f}")
    print(f"  Min:  {hog_features.min():.6f}")
    print(f"  Max:  {hog_features.max():.6f}")

    print("\n" + "=" * 80)
    print("Test complete!")
    print("=" * 80)


if __name__ == "__main__":
    main()
