# lower_face_config.py (With Feature Selection, SMOTE disabled, Moderate Weights)

import os

# Base paths
MODEL_DIR = 'models'
LOG_DIR = 'logs'

# Ensure directories exist
os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

# Model filenames
MODEL_FILENAMES = {
    'base_model': os.path.join(MODEL_DIR, 'lower_face_model.pkl'),
    'base_scaler': os.path.join(MODEL_DIR, 'lower_face_scaler.pkl'),
    'feature_importance': os.path.join(MODEL_DIR, 'lower_face_feature_importance.csv'),
    'feature_list': os.path.join(MODEL_DIR, 'lower_face_features.list')
    # Specialist files removed
}

# Define Core Lower Face Actions and AUs
LOWER_FACE_ACTIONS = ['BS', 'SS', 'SO', 'SE']
LOWER_FACE_AUS = [
    'AU10_r', 'AU12_r', 'AU14_r', 'AU15_r', 'AU17_r',
    'AU20_r', 'AU23_r', 'AU25_r', 'AU26_r'
]

# Feature extraction parameters
FEATURE_CONFIG = {
    'actions': LOWER_FACE_ACTIONS,
    'aus': LOWER_FACE_AUS,
    'use_normalized': False,
    'percent_diff_cap': 200.0,
    'min_value': 0.0001
}

# --- NEW: Feature Selection Configuration ---
FEATURE_SELECTION = {
    'enabled': True,           # Enable feature selection based on importance
    'top_n_features': 50,      # Number of top features to select (adjust as needed)
    'importance_file': MODEL_FILENAMES['feature_importance'] # File generated by previous training run
}
# --- End Feature Selection ---

# ML model training parameters (Simplified)
TRAINING_CONFIG = {
    'test_size': 0.25,
    'random_state': 42,
    'cv_folds': 5, # Used only if CV is run (optional in simplified training)

    # Base model parameters (XGBoost) - Using default-like params for now
    'base_model': {
        'objective': 'multi:softprob',
        'num_class': 3,
        'learning_rate': 0.1, # Default XGBoost
        'max_depth': 6,       # Common default
        'min_child_weight': 1, # Default XGBoost
        'subsample': 1.0,     # Default XGBoost
        'colsample_bytree': 1.0, # Default XGBoost
        'gamma': 0,           # Default XGBoost
        'n_estimators': 100,  # Default XGBoost
        # Moderate class weights
        'class_weights': {0: 1.0, 1: 3.0, 2: 3.0}
    },

    # SMOTE parameters - DISABLED
    'smote': {
        'enabled': True,
        'sampling_multiplier': 1.0, # Not used if disabled
        'k_neighbors': 5            # Not used if disabled
    }
}

# Detection thresholds REMOVED

# Class name mapping
CLASS_NAMES = {
    0: 'None',
    1: 'Partial',
    2: 'Complete'
}

# Logging configuration
LOGGING_CONFIG = {
    'level': 'INFO',
    'format': '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
}