"""Tier 2 — release-gate retrain reproducibility tests.
Total runtime budget: ≤ 15 minutes (3 zones × 2 data sources × ~1.5min each).

These tests answer: "if we retrain Mid/Upper/Lower face models from scratch
using the saved Jan 1 hyperparameters (use_known_optimal=True) on the
canonical training data (paper_combined_results.csv), do we land in a band
that's within tolerance of the manuscript-published numbers?"

Failure modes this catches:
  - sklearn / xgboost upgrade silently shifts where the gradient-boosted
    model lands at convergence (the cause of the original 10pp 'manuscript
    regression' that took weeks to localize)
  - Retrain stochasticity widens beyond historical bands due to
    SMOTE/class-weighting/threshold-optimization interaction
  - Optuna re-tuning becomes worse (a regression in the search space) such
    that even use_known_optimal=True can't recover

Procedure per test:
  1. Back up current combined_results.csv → S3O Results/
  2. Copy source CSV (paper or current pyfaceau) into combined_results.csv
  3. Set use_known_optimal=True for the zone via env override (we don't
     mutate paralysis_config.py — we monkey-patch the loaded module)
  4. Invoke paralysis_training_pipeline.py <zone> in a subprocess with
     PYTHONHASHSEED=42 OMP_NUM_THREADS=1
  5. Parse log for 'Overall Accuracy:' line
  6. Restore original combined_results.csv
  7. Assert acc in band

Bands are auto-derived from current-state observations + relaxation. Update
via update_goldens.py --stage retrain_bands (sub-PR 3 introduces this stage).
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import time
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))

from conftest import (  # noqa: E402
    DETERMINISM_ENV,
    PYFACEAU_COMBINED_CSV,
    S3_ROOT,
)


_ACCURACY_RX = re.compile(r"Overall Accuracy:\s*([\d.]+)")
_BAL_ACC_RX = re.compile(r"Balanced Accuracy:\s*([\d.]+)")


def _python() -> Path:
    """Path to the venv python. Must match the one tests are running in."""
    return Path(sys.executable)


def _build_wrapper(zone: str, source_csv: Path, label: str) -> Path:
    """Write a wrapper script that overrides INPUT_FILES + enables
    use_known_optimal, then runs paralysis_training_pipeline.py as __main__
    via runpy. Returns the wrapper path.

    CRITICAL: must be invoked as a wrapper (python wrapper.py), NOT as
    PYTHONSTARTUP — PYTHONSTARTUP only fires for interactive Python and is
    silently ignored for `python script.py` invocations. The earlier
    PYTHONSTARTUP-based version was a no-op: the patches never applied,
    Optuna kept running, and we attributed the resulting 5pp acc swing to
    "retrain stochasticity" when it was actually Optuna nondeterminism.

    We never touch the production combined_results.csv on disk — other
    tests can keep reading it concurrently.
    """
    wrapper = HERE / f"_tier2_wrapper_{zone}_{label}.py"
    wrapper.write_text(
        "# Auto-generated by test_tier2_release.py; safe to delete.\n"
        f"import sys, runpy\n"
        f"sys.path.insert(0, {str(S3_ROOT)!r})\n"
        f"import paralysis_config\n"
        f"paralysis_config.INPUT_FILES['results_csv'] = {str(source_csv)!r}\n"
        f"paralysis_config.ZONE_CONFIG[{zone!r}]['training']['hyperparameter_tuning']['use_known_optimal'] = True\n"
        f"sys.argv = ['paralysis_training_pipeline.py', {zone!r}]\n"
        f"runpy.run_path({str(S3_ROOT / 'paralysis_training_pipeline.py')!r}, run_name='__main__')\n"
    )
    return wrapper


def _run_training(zone: str, wrapper: Path, log_path: Path) -> int:
    env = {**os.environ, **DETERMINISM_ENV}
    with log_path.open("w") as f:
        result = subprocess.run(
            [str(_python()), str(wrapper)],
            cwd=str(S3_ROOT), env=env, stdout=f, stderr=subprocess.STDOUT,
            timeout=900,
        )
    return result.returncode


def _parse_metrics(log_path: Path) -> dict[str, float]:
    text = log_path.read_text()
    out: dict[str, float] = {}
    m = _ACCURACY_RX.search(text)
    if m:
        out["accuracy"] = float(m.group(1))
    m = _BAL_ACC_RX.search(text)
    if m:
        out["balanced_accuracy"] = float(m.group(1))
    return out


def _retrain_test_body(zone: str, source_label: str, source_csv: Path, metric_bands):
    """Common body for per-zone-per-source retrain tests."""
    if not source_csv.exists():
        pytest.skip(f"source CSV not present: {source_csv}")

    bands_section = metric_bands.get("stage6b_retrain_bands", {})
    zone_bands = bands_section.get(zone, {})
    if not zone_bands or "_status" in bands_section and "sub-PR 3" in bands_section.get("_status", ""):
        pytest.skip(
            f"stage6b_retrain_bands for '{zone}' not yet calibrated; "
            "run `python tests/update_goldens.py --stage retrain_bands` first."
        )
    acc_min = zone_bands.get(f"{source_label}_acc_min", zone_bands.get("acc_min"))
    acc_max = zone_bands.get(f"{source_label}_acc_max", zone_bands.get("acc_max"))
    if acc_min is None or acc_max is None:
        pytest.skip(f"no per-source bands for {zone}/{source_label} in metric_bands.yaml")

    wrapper = _build_wrapper(zone, source_csv, source_label)
    log_path = HERE / "_tier2_artifacts" / f"{zone}_{source_label}.log"
    log_path.parent.mkdir(exist_ok=True)
    try:
        t0 = time.perf_counter()
        rc = _run_training(zone, wrapper, log_path)
        dt = time.perf_counter() - t0
        assert rc == 0, (
            f"training subprocess exited {rc} for zone={zone} source={source_label}; "
            f"see {log_path}"
        )
        metrics = _parse_metrics(log_path)
        assert "accuracy" in metrics, (
            f"could not parse 'Overall Accuracy:' from {log_path}; "
            f"first 500 chars of log:\n{log_path.read_text()[:500]}"
        )
        acc = metrics["accuracy"]
        print(
            f"\n  zone={zone} source={source_label}: acc={acc:.4f} "
            f"(band [{acc_min:.3f}, {acc_max:.3f}], took {dt:.1f}s)"
        )
        assert acc_min <= acc <= acc_max, (
            f"Retrain accuracy regression: zone={zone} source={source_label} "
            f"acc={acc:.4f} outside band [{acc_min:.3f}, {acc_max:.3f}]\n"
            f"Full log: {log_path}"
        )
    finally:
        wrapper.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Per-zone × per-source tests
# ---------------------------------------------------------------------------


@pytest.mark.tier2
@pytest.mark.slow
@pytest.mark.parametrize("zone", ["mid", "upper", "lower"])
def test_retrain_paper_csv_with_known_optimal(zone, metric_bands):
    """Fresh retrain on `paper_combined_results.csv` (canonical training
    snapshot) with `use_known_optimal=True`. Acc must land in the
    paper-source band — these are the closest-to-manuscript-publishable
    reproductions we can produce today."""
    paper_csv = S3_ROOT / "paper_combined_results.csv"
    _retrain_test_body(zone, "paper", paper_csv, metric_bands)


@pytest.mark.tier2
@pytest.mark.slow
@pytest.mark.parametrize("zone", ["mid", "upper", "lower"])
def test_retrain_current_csv_with_known_optimal(zone, metric_bands):
    """Fresh retrain on today's pyfaceau combined_results.csv with
    `use_known_optimal=True`. Acc must land in the current-source band."""
    _retrain_test_body(zone, "current_pyfaceau", PYFACEAU_COMBINED_CSV, metric_bands)
